[package]
name = "cp-verse"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
assert_matches = "1.5.0"
env_logger = "0.11.8"
log = "0.4.27"
quick-xml = "0.38.0"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
